language: python

dist: xenial
sudo: false

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install coverage isort
  - pip install -r lancet/test/requirements.txt

script:
  - coverage erase
  - coverage run setup.py test
  - coverage report

after_success:
  - bash <(curl -s https://codecov.io/bash)
