language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install coverage isort
  - pip install -r tests/requirements.txt

script:
  - python setup.py test
  - python report
